name: Publish
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
            
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-${{ matrix.target }}"
          # Build everything
          dotnet publish WpfSelfContained/WpfSelfContained.csproj --framework net6.0-windows --runtime "${{ matrix.target }}" -p:PublishReadyToRun=true,PublishSingleFile=true,PublishSelfContained=true -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"
          
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
